export const T3_CLI_USAGE = [
  "One-time connection setup:",
  "  plannotator t3 login --url <T3 MCP URL>",
  "",
  "Opt in to the Claude hook with install.sh --with-t3, then restart the Claude provider session.",
  "Agents use ordinary plannotator review, annotate and last commands. The default plugin is unchanged.",
  "The hook discovers their originating T3 conversation automatically. The skill needs no changes.",
  "Uses T3's existing external MCP API; no Plannotator MCP server is added to the provider.",
  "",
  "Explicitly scoped diagnostics (not required for the normal agent flow):",
  "  plannotator t3 annotate <file | folder | URL>... --url <T3 MCP URL> --thread <id> [--gate] [--markdown]",
  "  plannotator t3 review [DIRECTORY | PR_URL] --url <T3 MCP URL> --thread <id> [--base <ref>]",
  "  plannotator t3 last --url <T3 MCP URL> --thread <id>",
  "  plannotator t3 list --url <T3 MCP URL> --thread <id>",
  "  plannotator t3 close <pn-id | all> --url <T3 MCP URL> --thread <id>",
  "  plannotator t3 status --url <T3 MCP URL> --thread <id>",
  "  plannotator t3 stop --url <T3 MCP URL> --thread <id>",
  "",
  "Diagnostic review launches return immediately; feedback arrives later in the selected conversation.",
  "Explicit diagnostic commands require a verified thread ID; never infer it from a title or folder.",
  "",
  "Options:",
  "  --data-dir <path>          Override the Plannotator data directory",
  "  --plannotator <executable> Override the review CLI (default: this Plannotator)",
  "",
  "Login opens T3's authorization page once. Other commands never open a login browser.",
  "Run these commands on the T3 environment's machine, where its project files are accessible.",
].join("\n");
